"""initial schema

Revision ID: 42945c753986
Revises:
Create Date: 2026-08-12 15:26:03.669841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import src.talentrank.db.types

# revision identifiers, used by Alembic.
revision: str = "42945c753986"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "match_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("resume_hash", sa.String(length=16), nullable=False),
        sa.Column("resume_text", sa.Text(), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("top_n", sa.Integer(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("filters_digest", sa.String(length=8), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("corpus_profile", sa.String(length=16), nullable=False),
        sa.Column("took_ms", sa.Float(), nullable=False),
        sa.Column("created_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_match_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_runs")),
    )
    with op.batch_alter_table("match_runs", schema=None) as batch_op:
        batch_op.create_index("ix_match_runs_user_created", ["user_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_match_runs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "saved_lists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("created_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_lists_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_lists")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_saved_lists_user_id")),
    )
    with op.batch_alter_table("saved_lists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saved_lists_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("revoked_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "match_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("match_run_id", sa.Uuid(), nullable=True),
        sa.Column("resume_hash", sa.String(length=16), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("signal", sa.String(length=16), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("created_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_run_id"],
            ["match_runs.id"],
            name=op.f("fk_match_feedback_match_run_id_match_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_match_feedback_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_feedback")),
        sa.UniqueConstraint("user_id", "match_run_id", "job_id", "signal", name=op.f("uq_match_feedback_user_id")),
    )
    with op.batch_alter_table("match_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_match_feedback_match_run_id"), ["match_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_match_feedback_user_id"), ["user_id"], unique=False)

    op.create_table(
        "saved_list_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("saved_list_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("job_title", sa.String(length=255), nullable=False),
        sa.Column("job_family", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", src.talentrank.db.types.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["saved_list_id"],
            ["saved_lists.id"],
            name=op.f("fk_saved_list_items_saved_list_id_saved_lists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_list_items")),
        sa.UniqueConstraint("saved_list_id", "job_id", name=op.f("uq_saved_list_items_saved_list_id")),
    )
    with op.batch_alter_table("saved_list_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saved_list_items_saved_list_id"), ["saved_list_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("saved_list_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_list_items_saved_list_id"))

    op.drop_table("saved_list_items")
    with op.batch_alter_table("match_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_feedback_user_id"))
        batch_op.drop_index(batch_op.f("ix_match_feedback_match_run_id"))

    op.drop_table("match_feedback")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("saved_lists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_lists_user_id"))

    op.drop_table("saved_lists")
    with op.batch_alter_table("match_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_runs_user_id"))
        batch_op.drop_index("ix_match_runs_user_created")

    op.drop_table("match_runs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
